### ISSUE TITLE
Game Capture doesn't work after installing

### ISSUE THREAD

**Issue by ktsuttlemyre** [HoneyHazard/PixelMatchSwitcher#10]
Hello, I was using obs for a few months without issue and now that I am using this install it seems to have broken the game capture element and I can not get it to work. I have tried uninstalling, deleting user data, and running in administrator mode. Please help. Is this a limitation of this build or do I need to configure something else to fix it?

**Comment by HoneyHazard** [comment]
Hello. Can you confirm the issue happens with the latest builds?
