### ISSUE TITLE
Frequent Crashes Upon Switching Scenes

### ISSUE THREAD

**Issue by ItsDatSpicymeme** [HoneyHazard/PixelMatchSwitcher#11]
When detecting if certain pixels on the video are matching or not, it will frequently crash when attempting to switch scenes or switch scene sources.  Only happens when "Enable Switching" is enabled.

[Crash 2021-09-06 16-31-47.txt](https://github.com/HoneyHazard/PixelMatchSwitcher/files/7117976/Crash.2021-09-06.16-31-47.txt)

**Comment by sbutylkov** [comment]
Hello. Sorry about slow response. Does this still happen with the latest version?

**Comment by sbutylkov** [comment]
There were source reference fixes since then. This might be fixed.
