### ISSUE TITLE
mac osx?

### ISSUE THREAD

**Issue by larsdpeder** [HoneyHazard/PixelMatchSwitcher#18]
Hi, Trying to test the osx dmg release but cant see the plugin in the "tools" menu. What am i doing wrong?  Its the 0.30.0 alpha 1 build i'm trying. Thanks.

**Comment by sbutylkov** [comment]
Hello. If you don't see it in the menu the plugin most likely fails to initialize. Check the OBS logs and you should be able to see error(s) related to Pixel Match Switcher

**Comment by HoneyHazard** [comment]
Can you check if the you are still having a problem with [0.34.0-alpha release](https://github.com/HoneyHazard/PixelMatchSwitcher/releases/tag/0.34.0-alpha)?

**Comment by larsdpeder** [comment]
works!

**Comment by HoneyHazard** [comment]
Awesome! All feedback is very welcome on the OSX version. It is not being tested by any of the developers as of the moment.
