### ISSUE TITLE
YT authentication module not working in builds

### ISSUE THREAD

**Issue by aidin** [HoneyHazard/PixelMatchSwitcher#19]
Hi there, the current embeded OBS version (Windows) is limited in its YouTube streaming functionality. Would be awesome if you could upgrade the fork to the latest OBS release, so the YouTube authenticated functionality becomes available. I really really really need this plugin but am blocked because of the missing YT module :(

**Comment by HoneyHazard** [comment]
Hello. Assuming you are talking about the builds, they are being kept up to date with stable OBS releases. If the functionality is present in the latest stable OBS but does not work in our builds I suspect it's a matter of building things right. I will take a look at how the YT module works

**Comment by HoneyHazard** [comment]
Do you see this page in settings? Does it not work? Can you show me your OBS logs? 

![image](https://user-images.githubusercontent.com/8847050/152115151-ab4c350c-07bf-4a70-9c3e-b05564aac010.png)

**Comment by aidin** [comment]
This is what I have, which lets me directly connect my YouTube account and would start/stop the stream from within OBS
<img width="982" alt="image" src="https://user-images.githubusercontent.com/6371339/152125987-d37480c5-5846-4c7c-aead-2db89b977d27.png">

**Comment by HoneyHazard** [comment]
> This is what I have, which lets me directly connect my YouTube account and would start/stop the stream from within OBS

I see. It's the connect account method.

**Comment by HoneyHazard** [comment]
Next release will have this feature. Stay tuned.

**Comment by HoneyHazard** [comment]
The functionality is available in [0.34.0-alpha release](https://github.com/HoneyHazard/PixelMatchSwitcher/releases/tag/0.34.0-alpha)
