### ISSUE TITLE
Linger/Cooldown not working?

### ISSUE THREAD

**Issue by calegendre** [HoneyHazard/PixelMatchSwitcher#20]
I can't seem to get linger/cooldown to work properly either with hotkey settings or individual scene item settings...

Thank you!

**Comment by HoneyHazard** [comment]
Hmm can you describe in detail what you are trying to do; video if possible? I will take a look in a few days

**Comment by calegendre** [comment]
Linger setting is supposed to keep an item on screen for X amount of time
(ms) after it unmatches, correct?

Will try to get a video - but even with linger set to 10000….when something
unmatches, it happens right away as if there wasn’t a linger value set!

Thanks. Absolutely no rush. What I’ve done for our stream thanks to your
stuff? I’m blown away. Thank you!

**Comment by HoneyHazard** [comment]
Hello and thank you for kind words,

Yes, linger delay should do what you are describing
https://github.com/HoneyHazard/PixelMatchSwitcher/wiki/User-Manual#linger-delay


In the near future I will do more testing to see if I can reproduce your situation

**Comment by HoneyHazard** [comment]
Hello, confirming that yes, linger and cooldown are not working as expected.

Fix is coming soon.

**Comment by HoneyHazard** [comment]
New release will contain the fix. Hope to have it out in a few days.

**Comment by HoneyHazard** [comment]
Lots of fixes for lingers and cooldowns are in [0.34.0-alpha release](https://github.com/HoneyHazard/PixelMatchSwitcher/releases/tag/0.34.0-alpha). If you keep running into similar or other problems please make a new issue. Thank you for testing and reporting :)
