### ISSUE TITLE
Request: More Frequent MacOS builds & SElive question 

### ISSUE THREAD

**Issue by calegendre** [HoneyHazard/PixelMatchSwitcher#21]
I would like to see more macOS releases when updated if possible. My more powerful machine is my Mac and I feel it would be helpful to run everything on there….

also, what do we gain from SElive/SFX without an account? I haven’t signed up and I think at one point I accidentally nuked it from the install because the splash screen was bothering me: does this break anything? 

Thanks again so much.

**Comment by HoneyHazard** [comment]
Hello! There is an issue with automated OSX builds that needs to be resolved.

Bundled plugins are included to make life easier for the users.

For SE.live you have an option of installing or not installing it.

**Comment by calegendre** [comment]
I know nothing about SElive but I see that when I pulled the latest win
update there were two different installers and the one I went with didn’t
have it (don’t know it’s benefits, just knew it nagged me)

I have a decent iMac I would test builds but I’m not a developer so I’m not
necessarily set up for it — but I’m willing to test things if instructions
are there.

Thank you for your hard work!

**Comment by HoneyHazard** [comment]
Automated OSX builds are back in [0.34.0-alpha release](https://github.com/HoneyHazard/PixelMatchSwitcher/releases/tag/0.34.0-alpha)
