### ISSUE TITLE
switch while always monitoring specific input?

### ISSUE THREAD

**Issue by ke5stl** [HoneyHazard/PixelMatchSwitcher#3]
Can this plugin be used to always monitor video of a specific source (live or not), and, based on whether it contains the matching mask content, decide which scene to make 'live'?

eg: video of game that has scoreboard at a given location.

If I want to replace the adverts that may be shown, it would notice that the scoreboard is no longer shown, and switch to another scene.  meanwhile, the input video is still being monitored, so that it can be switched back to 'live' when the scoreboard returns?

**Comment by HoneyHazard** [comment]
Hi ke5stl,

The answer is yes, but it may be slightly awkward. 

Current requirement is that the source that is being monitored *has to be* in the currently active scene. In other words, if the source is only present in the scene(s) that are not active, it will *not* be monitored.

It should be possible to work around this by including your source in all scenes that may be active. Even if there is no desire to display the source in all scenes, you should be able to inconspicuously placing it behind source(s) being shown in the front. If all else fails, you could try making it visible and in the front but very tiny.

Please let me know if such workarounds end up working for you. It may be good to make a note of this in the user manual.

At the moment I don't think it will be possible to monitor sources that do not appear at all in the current scene. My understanding is that OBS just does not pipe any video through sources when they are not active. If there are way to force them to be active, while monitored, it could be very hacky and I will give no guarantee of it working.

**Comment by HoneyHazard** [comment]
any luck?
