### ISSUE TITLE
Virtual Camera Support

### ISSUE THREAD

**Issue by cjbarth** [HoneyHazard/PixelMatchSwitcher#5]
I got this installed and running, and it is truly amazing... just what I needed. I note that this build of OBS doesn't include the virtual camera. Did I do something wrong?

**Comment by HoneyHazard** [comment]
Most likely the issue is on our end. I've been working to make sure that Windows builds have as many features as people want, and I will take a look into checking for virtual camera support as well.

**Comment by HoneyHazard** [comment]
I've identified the problem with how I'm doing the windows builds. Expect a fixed release today

**Comment by HoneyHazard** [comment]
Windows builds have been update to support virtual camera functionality. For convenience, the plugin is included with installation and direct show filters will be registered during installation.

https://github.com/HoneyHazard/PixelMatchSwitcher/releases/tag/0.29.3-alpha

**Comment by cjbarth** [comment]
I see that you included the plugin, which is great, however, the v26 release of OBS includes a Wizard that will set up an included Virtual Camera instead of using the plug in. That setup routine will include a button to start and stop the virtual camera in the Controls pane. I'm wondering if that functionality could be included instead of just the plug-in.

This is what I'm looking for: https://www.nextofwindows.com/how-to-use-obss-virtual-camera

From https://obsproject.com/welcome:

Latest Updates
OBS Studio 26.0
Official Virtual Cam

Added official Virtual Camera support on Windows, allowing you to use the OBS output as a camera in other apps on your computer. Support for other operating systems will be added in future versions when they're ready.

**Comment by HoneyHazard** [comment]
I see what you are talking about, and apologize for jumping too quick to a possibly suboptimal solution.

It looks like this functionality may be not building, for whatever reason. I will take a closer look soon.

**Comment by HoneyHazard** [comment]
Hello,

I got rid of the plugin and have a version which should be giving you the native virtual camera support

Please take a look:

https://github.com/HoneyHazard/PixelMatchSwitcher/releases/tag/0.30.0-alpha

**Comment by cjbarth** [comment]
I've noticed that there is still something fishy going on here. There seems to be a command shell that runs to install the virtual camera, whereas the official v26 build doesn't do that. Also, I note that I now have two virtual cameras from OBS: one is installed by your build, the other is installed by official builds. Thus, it appears that there is still something wrong with they way your build includes the camera. Reopening...

**Comment by HoneyHazard** [comment]
> There seems to be a command shell that runs to install the virtual camera, whereas the official v26 build doesn't do that

Please, do not worry about that. I've changed the installer to use the batch script officially recommended by OBS wiki, which in my experience gave better results.



> Also, I note that I now have two virtual cameras from OBS: one is installed by your build, the other is installed by official builds

Most likely this is because of different GUIDs being used in our build, even though I tried to use the same one as official OBS. While this may be annoying, the change is most likely superficial.

**Comment by HoneyHazard** [comment]
Should be taken care of with the official camera GUID used
